require: rubocop-rspec

AllCops:
  NewCops: enable

# FIXME using json may be better
Security/MarshalLoad:
  Enabled: false


Gemspec/OrderedDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
